image:
  file: flow.Dockerfile
vscode:
  extensions:
    - "redhat.vscode-yaml"
checkoutLocation: "/workspace"
workspaceLocation: "/workspace/flow"
tasks:
  - name: Initialize Flow CLI
    init: /workspace/init.sh